// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"apiserver-gin/internal/handler/v1"
	"apiserver-gin/internal/handler/v1/accountbill"
	"apiserver-gin/internal/handler/v1/user"
	"apiserver-gin/internal/repo/mysql"
	"apiserver-gin/internal/router"
	"apiserver-gin/internal/service"
	"apiserver-gin/pkg/db"
	"apiserver-gin/server"
	"github.com/google/wire"
)

// Injectors from wire.go:

func initRouter(ds db.IDataSource) server.Router {
	userRepo := mysql.NewUserRepo(ds)
	userService := service.NewUserService(userRepo)
	handler := user.NewUserHandler(userService)
	accountBillRepo := mysql.NewAccountBillRepo(ds)
	accountBillService := service.NewAccountBillService(accountBillRepo)
	accountbillHandler := accountbill.NewAccountBillHandler(accountBillService)
	apiRouter := router.NewApiRouter(handler, accountbillHandler)
	return apiRouter
}

// wire.go:

var providerSet = wire.NewSet(mysql.ProviderSet, service.ProviderSet, v1.ProviderSet)
