// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"apiserver-gin/internal/handler/v1"
	"apiserver-gin/internal/handler/v1/accountbill"
	"apiserver-gin/internal/handler/v1/user"
	"apiserver-gin/internal/middleware"
	"apiserver-gin/internal/repo/mysql"
	"apiserver-gin/internal/router"
	"apiserver-gin/internal/service"
	"apiserver-gin/pkg/db"
	"apiserver-gin/server"
	"github.com/google/wire"
)

// Injectors from wire.go:

func buildUserRouter(ds db.IDataSource) server.Router {
	userRepo := mysql.NewUserRepo(ds)
	userService := service.NewUserService(userRepo)
	handler := user.NewUserHandler(userService)
	userRouter := router.NewUserRouter(handler)
	return userRouter
}

func buildAccountBillRouter(ds db.IDataSource) server.Router {
	accountBillRepo := mysql.NewAccountBillRepo(ds)
	accountBillService := service.NewAccountBillService(accountBillRepo)
	handler := accountbill.NewAccountBillHandler(accountBillService)
	accountBillRouter := router.NewAccountBillRouter(handler)
	return accountBillRouter
}

// wire.go:

// getRouters 获取所有的router
func getRouters(ds db.IDataSource) []server.Router {
	rts := make([]server.Router, 0)

	rts = append(rts, middleware.NewMiddleware(), buildUserRouter(ds),
		buildAccountBillRouter(ds),
	)
	return rts
}

var providerSet = wire.NewSet(mysql.ProviderSet, service.ProviderSet, v1.ProviderSet)
