// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"apiserver-gin/internal/handler/v1/user"
	"apiserver-gin/internal/middleware"
	"apiserver-gin/internal/repo/mysql"
	"apiserver-gin/internal/router"
	"apiserver-gin/internal/service"
	"apiserver-gin/pkg/db"
	"apiserver-gin/server"
)

// Injectors from wire.go:

func initRouter(ds db.IDataSource) server.Router {
	userRepo := mysql.NewUserRepo(ds)
	userService := service.NewUserService(userRepo)
	userHandler := user.NewUserHandler(userService)
	userRouter := router.NewUserRouter(userHandler)
	return userRouter
}

// wire.go:

// getRouters 获取所有的router
func getRouters(ds db.IDataSource) []server.Router {
	rts := make([]server.Router, 0)
	rts = append(rts, middleware.NewMiddleware())
	urt := initRouter(ds)
	if urt != nil {
		rts = append(rts, urt)
	}
	return rts
}
